<?php
/**
 * Netcrafter — Bilingual translation engine (FR / EN)
 * Include this file once before any output.
 * Usage: t('key') or t('key', 'en')
 */

if (session_status() === PHP_SESSION_NONE) session_start();

// Switch language via GET param: ?lang=en or ?lang=fr
if (isset($_GET['lang']) && in_array($_GET['lang'], ['fr','en'])) {
    $_SESSION['nc_lang'] = $_GET['lang'];
}
$GLOBALS['nc_lang'] = $_SESSION['nc_lang'] ?? 'fr';

function t(string $key, ?string $forceLang = null): string {
    $lang = $forceLang ?? $GLOBALS['nc_lang'];
    $d = $GLOBALS['nc_translations'] ?? [];
    return htmlspecialchars($d[$lang][$key] ?? $d['fr'][$key] ?? $key, ENT_QUOTES, 'UTF-8');
}
function tr(string $key): string {   // raw — no htmlspecialchars (for HTML content)
    $lang = $GLOBALS['nc_lang'];
    $d = $GLOBALS['nc_translations'] ?? [];
    return $d[$lang][$key] ?? $d['fr'][$key] ?? $key;
}

$GLOBALS['nc_translations'] = [

/* ══════════════════════════════════════════════════════════════
   NAVIGATION & GLOBAL
══════════════════════════════════════════════════════════════ */
'fr' => [
    // Nav
    'nav.home'          => 'Accueil',
    'nav.services'      => 'Services',
    'nav.shop'          => 'Boutique',
    'nav.training'      => 'Formation',
    'nav.panels'        => 'Nos Volets',
    'nav.portfolio'     => 'Portfolio',
    'nav.blog'          => 'Blog',
    'nav.quote'         => 'Devis Gratuit',
    'nav.lang_switch'   => 'EN',
    'nav.lang_current'  => 'FR',
    'nav.account'       => 'Mon Compte',
    'nav.dashboard'     => 'Tableau de bord',
    'nav.my_formations' => 'Mes formations',
    'nav.certificates'  => 'Mes certificats',
    'nav.edit_profile'  => 'Modifier profil',
    'nav.logout'        => 'Déconnexion',
    'nav.login'         => 'Connexion',
    'nav.resources'     => 'Ressources',
    'nav.process'       => 'Notre Processus',
    'nav.stack'         => 'Stack Technique',
    'nav.tools'         => 'Outils',
    'nav.configurator'  => 'Configurateur',
    'nav.audit'         => 'Audit de site',
    'nav.palette'       => 'Palette couleurs',
    'nav.seo_preview'   => 'Aperçu SEO',

    // Footer
    'footer.desc'       => 'Solutions numériques professionnelles pour le marché africain. Web, sécurité, formation et bien plus.',
    'footer.nav'        => 'Navigation',
    'footer.services'   => 'Services',
    'footer.contact'    => 'Contact',
    'footer.dev_web'    => 'Développement Web',
    'footer.marketing'  => 'Marketing Digital',
    'footer.cctv'       => 'Vidéosurveillance',
    'footer.network'    => 'Réseaux',
    'footer.maintenance'=> 'Maintenance',
    'footer.rights'     => 'Tous droits réservés.',
    'footer.privacy'    => 'Confidentialité',
    'footer.tos'        => 'CGU',
    'footer.legal'      => 'Mentions légales',
    'footer.whatsapp'   => 'WhatsApp Direct',

    // Common buttons/actions
    'btn.quote'         => 'Devis Gratuit',
    'btn.discover'      => 'Découvrir',
    'btn.contact'       => 'Nous contacter',
    'btn.learn_more'    => 'En savoir plus',
    'btn.send'          => 'Envoyer',
    'btn.submit'        => 'Soumettre',
    'btn.back'          => 'Retour',
    'btn.see_all'       => 'Voir tout',
    'btn.our_services'  => 'Voir nos services',
    'btn.free_quote'    => 'Devis gratuit',
    'btn.view_details'  => 'Voir les détails',

    // Status
    'available'         => 'Disponible pour de nouveaux projets',
    'results_guaranteed'=> 'Résultats garantis, délais respectés.',

    /* ── Index page ──────────────────────────────────────────── */
    'home.hero_title'   => 'Transformez<br>votre vision<br><span class="gradient-text">numérique.</span>',
    'home.hero_sub'     => 'Expert en développement web, sécurité informatique, marketing digital et formation professionnelle.',
    'home.stat_clients' => 'Clients satisfaits',
    'home.stat_projects'=> 'Projets livrés',
    'home.stat_years'   => "Années d'expérience",
    'home.about_badge'  => 'À Propos',
    'home.about_title'  => 'Votre Partenaire Numérique de Confiance',
    'home.about_sub'    => "Netcrafter est une entreprise nigérienne spécialisée dans les solutions numériques pour les PME et institutions de la région.",
    'home.services_badge'=> 'Nos Services',
    'home.services_title'=> 'Tout ce dont vous avez besoin',
    'home.services_sub' => 'Des solutions complètes pour votre transformation numérique',
    'home.cta_title'    => 'Prêt à transformer votre présence numérique ?',
    'home.cta_sub'      => "Rejoignez plus de 150 clients qui nous font confiance. Devis gratuit et sans engagement.",

    /* ── Services page ───────────────────────────────────────── */
    'services.badge'    => 'Nos Services',
    'services.title'    => 'Solutions Numériques Complètes',
    'services.sub'      => 'De la conception à la livraison, nous gérons chaque aspect de votre projet numérique.',
    'services.dev_web'  => 'Développement Web',
    'services.marketing'=> 'Marketing Digital',
    'services.security' => 'Sécurité & CCTV',
    'services.network'  => 'Réseaux & Infra',
    'services.training' => 'Formation Pro',
    'services.maintenance'=>'Maintenance IT',

    /* ── Volets page ─────────────────────────────────────────── */
    'volets.badge'      => 'Nos Volets',
    'volets.title'      => 'Domaines d\'Excellence',
    'volets.sub'        => 'Nous intervenons sur 6 grands domaines technologiques pour couvrir tous vos besoins.',

    /* ── Portfolio page ──────────────────────────────────────── */
    'portfolio.badge'   => 'Portfolio',
    'portfolio.title'   => 'Nos Réalisations',
    'portfolio.sub'     => 'Découvrez quelques-uns de nos projets récents.',
    'portfolio.filter_all'=> 'Tous',

    /* ── Devis page ──────────────────────────────────────────── */
    'devis.badge'       => 'Devis Gratuit',
    'devis.title'       => 'Obtenez Votre Devis',
    'devis.sub'         => 'Répondez à quelques questions et recevez une estimation sous 24h.',
    'devis.name'        => 'Nom complet',
    'devis.email'       => 'Adresse email',
    'devis.phone'       => 'Téléphone',
    'devis.company'     => 'Entreprise (optionnel)',
    'devis.service'     => 'Service souhaité',
    'devis.budget'      => 'Budget estimé',
    'devis.message'     => 'Description du projet',
    'devis.send'        => 'Envoyer ma demande',
    'devis.success'     => 'Votre demande a été envoyée ! Nous vous répondrons sous 24h.',

    /* ── Index extra ────────────────────────────────────────── */
    'home.what_we_do'   => 'Ce que nous faisons',
    'home.what_we_master'=> 'Ce que nous maîtrisons',
    'home.experts_title'=> 'Expertises Technologiques',
    'home.trust'        => 'Ils nous font confiance',
    'home.testimonials' => 'Ce que disent nos clients',
    'home.tech_title'   => 'Technologies que nous maîtrisons',
    'home.volets_badge' => 'Notre écosystème',
    'home.volets_title' => '3 Volets, <span class="gradient-text">1 Vision</span>',
    'home.cta_badge'    => 'Action maintenant',
    'home.cta_action'   => 'Votre prochain projet commence <span class="gradient-text">maintenant</span>',
    'home.cta_action_sub'=> 'Discutons de vos besoins et construisons ensemble la solution qui propulsera votre activité.',
    'home.devis_24h'    => 'Devis gratuit — 24h',
    'home.whatsapp_direct'=> 'WhatsApp direct',
    'home.need_solution'=> "Vous avez besoin d'une de ces solutions ?",
    'home.all_services' => 'Tous nos services',
    'home.see_our_work' => 'Voir nos réalisations',
    'home.see_all_projects'=> 'Voir tous les projets',
    'home.portfolio_soon'=> 'Portfolio bientôt disponible.',
    'home.ecosystem'    => 'Notre écosystème',
    'home.stat_done'    => 'Projets réalisés',
    'home.stat_exp'     => "D'expertise",

    /* ── Services page extra ─────────────────────────────────── */
    'services.design'   => 'Design Graphique',
    'services.it'       => 'Informatique',
    'services.hero_sub' => 'Solutions numériques complètes, de la conception au déploiement. Expertise locale, standards internationaux.',
    'services.cta_badge'=> 'Prêt à démarrer ?',
    'services.cta_title'=> 'Prêt à démarrer <span class="gradient-text">votre projet ?</span>',
    'services.cta_sub'  => "Contactez-nous dès aujourd'hui pour un devis personnalisé gratuit.",

    /* ── Volets extra ────────────────────────────────────────── */
    'volets.our_org'    => 'Notre organisation',
    'volets.cta_title'  => 'Une question sur nos volets ?',
    'volets.cta_sub'    => 'Contactez-nous pour un accompagnement personnalisé.',

    /* ── Portfolio labels ────────────────────────────────────── */
    'pf.all'            => 'Tous',
    'pf.dev_web'        => 'Dev Web',
    'pf.webview'        => 'WebView',
    'pf.ia_chatbot'     => 'IA & Chatbot',
    'pf.whatsapp'       => 'WhatsApp',
    'pf.gestion'        => 'Gestion',
    'pf.suivi'          => 'Suivi',
    'pf.design'         => 'Design',
    'pf.securite'       => 'Sécurité',

    /* ── Devis selects ───────────────────────────────────────── */
    'devis.budget_ph'   => 'Sélectionnez une fourchette',
    'devis.b_under50'   => 'Moins de 50 000 FCFA',
    'devis.b_50_100'    => '50 000 – 100 000 FCFA',
    'devis.b_100_300'   => '100 000 – 300 000 FCFA',
    'devis.b_300_500'   => '300 000 – 500 000 FCFA',
    'devis.b_over500'   => 'Plus de 500 000 FCFA',
    'devis.delay_ph'    => 'Sélectionnez un délai',
    'devis.d_urgent'    => 'Urgent (moins de 2 semaines)',
    'devis.d_1m'        => '1 mois',
    'devis.d_2_3m'      => '2–3 mois',
    'devis.d_flex'      => 'Flexible / À discuter',

    /* ── Devis services ──────────────────────────────────────── */
    'devis.svc_web'     => 'Développement Web',
    'devis.svc_web_sub' => 'Sites, apps, e-commerce',
    'devis.svc_mkt'     => 'Marketing Digital',
    'devis.svc_mkt_sub' => 'Ads, réseaux, contenu',
    'devis.svc_design'  => 'Design Graphique',
    'devis.svc_design_sub'=> 'Flyers, logos, identité',
    'devis.svc_secu'    => 'Sécurité & Surveillance',
    'devis.svc_secu_sub'=> 'Caméras, alarmes, accès',
    'devis.svc_it'      => 'Services Informatiques',
    'devis.svc_it_sub'  => 'Maintenance, réseau, cloud',
    'devis.svc_form'    => 'Formation',
    'devis.svc_form_sub'=> 'Formations sur mesure',

    /* ── Home services (section Nos Services) ────────────────── */
    'home.svc1_title'   => 'Développement Web',
    'home.svc1_desc'    => 'Sites vitrines, e-commerce, apps web sur mesure adaptés à vos objectifs.',
    'home.svc1_i1'      => 'Sites corporatifs & vitrines',
    'home.svc1_i2'      => 'Apps web sur mesure',
    'home.svc1_i3'      => 'E-commerce complet',
    'home.svc2_title'   => 'Marketing Digital',
    'home.svc2_desc'    => 'Campagnes publicitaires et stratégies de croissance pour vos ventes en ligne.',
    'home.svc2_i1'      => 'Facebook & Google Ads',
    'home.svc2_i2'      => 'Gestion réseaux sociaux',
    'home.svc2_i3'      => 'Stratégie de contenu',
    'home.svc3_title'   => 'Design Graphique',
    'home.svc3_desc'    => 'Identité visuelle professionnelle, flyers, bâches et supports impactants.',
    'home.svc3_i1'      => 'Flyers & dépliants',
    'home.svc3_i2'      => 'Identité visuelle',
    'home.svc3_i3'      => 'Bâches & vinyles',
    'home.svc4_title'   => 'Sécurité & Surveillance',
    'home.svc4_desc'    => "Vidéosurveillance, systèmes d'alarme et sécurité informatique.",
    'home.svc4_i1'      => 'Vidéosurveillance CCTV',
    'home.svc4_i2'      => "Systèmes d'alarme",
    'home.svc4_i3'      => "Contrôle d'accès",
    'home.svc5_title'   => 'Réseaux & Téléphonie',
    'home.svc5_desc'    => 'Conception et déploiement de réseaux et systèmes téléphoniques PABX.',
    'home.svc5_i1'      => 'Câblage réseau',
    'home.svc5_i2'      => 'Téléphonie PABX',
    'home.svc5_i3'      => 'Configuration serveurs',
    'home.svc6_title'   => 'Maintenance Info.',
    'home.svc6_desc'    => 'Maintenance préventive, réparation matériel et personnalisation systèmes.',
    'home.svc6_i1'      => 'Maintenance préventive',
    'home.svc6_i2'      => 'Réparation matériel',
    'home.svc6_i3'      => 'Customisation PC',

    /* ── Portfolio extra ─────────────────────────────────────── */
    'portfolio.featured'=> 'Projets mis en avant',
    'portfolio.all_proj'=> 'Tous les projets',
    'portfolio.no_cat'  => 'Aucun projet dans cette catégorie pour l\'instant.',
    'portfolio.see_proj'=> 'Voir le projet',
    'portfolio.similar' => 'Projet similaire ?',
    'portfolio.cta_badge'=> 'Votre projet',
    'portfolio.cta_title'=> 'Vous avez un projet <span class="gradient-text">similaire ?</span>',
    'portfolio.cta_sub' => 'Contactez-nous pour un devis gratuit et discutons de votre idée.',
    'portfolio.see_all' => 'Voir tous les projets',
    'portfolio.stat_done'=> 'Projets réalisés',
    'portfolio.stat_sat' => 'Clients satisfaits',
    'portfolio.stat_tech'=> 'Technologies maîtrisées',

    /* ── Devis extra ─────────────────────────────────────────── */
    'devis.form_badge'  => '100% gratuit, sans engagement',
    'devis.form_title'  => 'Formulaire de devis',
    'devis.fill_below'  => 'Remplissez les informations ci-dessous',
    'devis.info_step'   => 'Vos informations',
    'devis.services_step'=> 'Services souhaités',
    'devis.select_svcs' => 'Sélectionnez un ou plusieurs services :',
    'devis.project_step'=> 'Détails du projet',
    'devis.budget_label'=> 'Budget estimé',
    'devis.delay_label' => 'Délai souhaité',
    'devis.desc_label'  => 'Description du projet',
    'devis.how_found'   => 'Comment nous avez-vous connu ?',
    'devis.reset'       => 'Réinitialiser',
    'devis.send_request'=> 'Envoyer ma demande',
    'devis.why_us'      => 'Pourquoi nous choisir ?',
    'devis.contact_dir' => 'Nous contacter directement',
    'devis.testimonials'=> 'Ce que disent nos clients',
    'devis.faq'         => 'Questions fréquentes',
    'devis.company_opt' => "Nom de votre entreprise (optionnel)",
    'devis.desc_placeholder'=> 'Décrivez vos besoins, objectifs et attentes...',
    'devis.step_info'   => 'Informations',
    'devis.step_svcs'   => 'Services',
    'devis.step_project'=> 'Projet',

    /* ── Shop ────────────────────────────────────────────────── */
    'shop.title'        => 'Boutique',
    'shop.subtitle'     => 'Équipements et solutions technologiques',
    'shop.search'       => 'Rechercher un produit...',
    'shop.filters'      => 'Filtres',
    'shop.category'     => 'Catégorie',
    'shop.all_cats'     => 'Toutes les catégories',
    'shop.sort'         => 'Trier par',
    'shop.newest'       => 'Plus récent',
    'shop.price_asc'    => 'Prix croissant',
    'shop.price_desc'   => 'Prix décroissant',
    'shop.in_stock'     => 'En stock uniquement',
    'shop.no_results'   => 'Aucun produit trouvé.',
    'shop.add_cart'     => 'Ajouter au panier',
    'shop.add_fav'      => 'Favoris',
    'shop.in_cart'      => 'Dans le panier',
    'shop.out_stock'    => 'Rupture de stock',
    'shop.details'      => 'Détails',
    'shop.buy'          => 'Acheter',
    'shop.cart_title'   => 'Mon Panier',
    'shop.cart_empty'   => 'Votre panier est vide',
    'shop.cart_empty_sub'=> 'Parcourez notre boutique pour ajouter des produits.',
    'shop.total'        => 'Total',
    'shop.subtotal'     => 'Sous-total',
    'shop.shipping'     => 'Livraison',
    'shop.free_ship'    => 'Gratuite',
    'shop.checkout'     => 'Passer la commande',
    'shop.continue'     => 'Continuer mes achats',
    'shop.remove'       => 'Supprimer',
    'shop.qty'          => 'Qté',
    'shop.fav_title'    => 'Mes Favoris',
    'shop.fav_empty'    => 'Aucun favori',
    'shop.fav_empty_sub'=> "Cliquez sur le cœur d'un produit pour le sauvegarder.",
    'shop.clear_fav'    => 'Vider les favoris',
    'shop.view_cart'    => 'Voir mon panier',
    'shop.checkout_title'=> 'Finaliser la commande',
    'shop.order_summary'=> 'Récapitulatif',
    'shop.delivery_info'=> 'Informations de livraison',
    'shop.payment'      => 'Paiement',
    'shop.place_order'  => 'Valider la commande',
    'shop.order_success'=> 'Commande passée avec succès !',
    'shop.stock_low'    => 'Plus que',
    'shop.stock_low2'   => 'en stock',

    /* ── Formation ───────────────────────────────────────────── */
    'form.title'        => 'Formations',
    'form.subtitle'     => 'Développez vos compétences numériques',
    'form.search'       => 'Rechercher une formation...',
    'form.all_levels'   => 'Tous les niveaux',
    'form.beginner'     => 'Débutant',
    'form.intermediate' => 'Intermédiaire',
    'form.advanced'     => 'Avancé',
    'form.free_only'    => 'Gratuit uniquement',
    'form.subscribe'    => "S'inscrire",
    'form.continue'     => 'Continuer',
    'form.enrolled'     => 'Inscrit',
    'form.per_month'    => '/ mois',
    'form.free'         => 'Gratuit',
    'form.modules'      => 'modules',
    'form.videos'       => 'vidéos',
    'form.duration'     => 'Durée',
    'form.level'        => 'Niveau',
    'form.language'     => 'Langue',
    'form.login_title'  => 'Se connecter',
    'form.login_sub'    => 'Accédez à votre espace formation',
    'form.register_title'=> "S'inscrire",
    'form.register_sub' => 'Créez votre compte',
    'form.phone'        => 'Téléphone',
    'form.password'     => 'Mot de passe',
    'form.confirm_pass' => 'Confirmer le mot de passe',
    'form.firstname'    => 'Prénom',
    'form.lastname'     => 'Nom',
    'form.remember'     => 'Se souvenir de moi',
    'form.forgot'       => 'Mot de passe oublié ?',
    'form.no_account'   => 'Pas encore de compte ?',
    'form.has_account'  => 'Déjà un compte ?',
    'form.dashboard'    => 'Tableau de bord',
    'form.my_formations'=> 'Mes formations',
    'form.certificates' => 'Certificats',
    'form.profile'      => 'Profil',
    'form.logout'       => 'Se déconnecter',
    'form.progress'     => 'Progression',
    'form.watch_now'    => 'Regarder',
    'form.no_formations'=> 'Aucune formation disponible',
    'form.popular'      => 'Formations populaires',
    'form.all_formations'=> 'Toutes les formations',
    'form.cert_download'=> 'Télécharger le certificat',
    'form.filters'      => 'Filtres',
    'form.categories'   => 'Catégories',
    'form.all_cats'     => 'Toutes les catégories',
    'form.sort_by'      => 'Trier par',
    'form.sort_newest'  => 'Plus récents',
    'form.sort_price_asc'  => 'Prix croissant',
    'form.sort_price_desc' => 'Prix décroissant',
    'form.sort_alpha'   => 'Alphabétique',
    'form.apply_filters'=> 'Appliquer les filtres',
    'form.reset_filters'=> 'Réinitialiser les filtres',
    'form.search_btn'   => 'Rechercher',
    'form.filter_btn'   => 'Filtres',
    'form.results_for'  => 'Résultats pour',
    'form.cat_label'    => 'Catégorie :',
    'form.found'        => 'formations trouvées',
    'form.discover'     => 'Découvrir',
    'form.not_found_title' => 'Aucune formation trouvée',
    'form.not_found_sub'   => "Nous n'avons pas trouvé de formations correspondant à vos critères. Essayez de modifier vos filtres ou votre recherche.",
    'form.testimonials' => 'Ce que disent nos apprenants',
    'form.cta_title'    => 'Vous ne trouvez pas votre formation idéale ?',
    'form.cta_sub'      => 'Contactez-nous pour discuter de vos besoins spécifiques. Nous pouvons créer des parcours de formation personnalisés.',
    'form.contact_us'   => 'Nous contacter',
    'form.pro_title'    => 'Formations Professionnelles',
    'form.pro_sub'      => 'Contenu de qualité conçu par des experts du domaine',
    'form.rhythm_title' => 'À Votre Rythme',
    'form.rhythm_sub'   => 'Apprenez quand vous voulez, où vous voulez',
    'form.cert_title'   => 'Certificats Validés',
    'form.cert_sub'     => 'Obtenez une attestation à la fin de votre parcours',
    'form.community_title' => 'Forum Communautaire',
    'form.community_sub'   => "Échangez avec des formateurs et d'autres apprenants",
    'form.var_duration' => 'Durée variable',
    'form.see_all'      => 'Voir toutes les formations',
    'form.favorites'    => 'Mes formations favorites',
    'form.notes_hint'   => 'Prenez des notes sur cette vidéo...',
],

/* ══════════════════════════════════════════════════════════════
   ENGLISH
══════════════════════════════════════════════════════════════ */
'en' => [
    // Nav
    'nav.home'          => 'Home',
    'nav.services'      => 'Services',
    'nav.shop'          => 'Shop',
    'nav.training'      => 'Training',
    'nav.panels'        => 'Our Sectors',
    'nav.portfolio'     => 'Portfolio',
    'nav.blog'          => 'Blog',
    'nav.quote'         => 'Free Quote',
    'nav.lang_switch'   => 'FR',
    'nav.lang_current'  => 'EN',
    'nav.account'       => 'My Account',
    'nav.dashboard'     => 'Dashboard',
    'nav.my_formations' => 'My trainings',
    'nav.certificates'  => 'My certificates',
    'nav.edit_profile'  => 'Edit profile',
    'nav.logout'        => 'Sign out',
    'nav.login'         => 'Sign in',
    'nav.resources'     => 'Resources',
    'nav.process'       => 'Our Process',
    'nav.stack'         => 'Tech Stack',
    'nav.tools'         => 'Tools',
    'nav.configurator'  => 'Configurator',
    'nav.audit'         => 'Site Audit',
    'nav.palette'       => 'Color palette',
    'nav.seo_preview'   => 'SEO Preview',

    // Footer
    'footer.desc'       => 'Professional digital solutions for the African market. Web, security, training and much more.',
    'footer.nav'        => 'Navigation',
    'footer.services'   => 'Services',
    'footer.contact'    => 'Contact',
    'footer.dev_web'    => 'Web Development',
    'footer.marketing'  => 'Digital Marketing',
    'footer.cctv'       => 'Video Surveillance',
    'footer.network'    => 'Networks',
    'footer.maintenance'=> 'Maintenance',
    'footer.rights'     => 'All rights reserved.',
    'footer.privacy'    => 'Privacy',
    'footer.tos'        => 'Terms',
    'footer.legal'      => 'Legal notice',
    'footer.whatsapp'   => 'WhatsApp Direct',

    // Common buttons
    'btn.quote'         => 'Free Quote',
    'btn.discover'      => 'Discover',
    'btn.contact'       => 'Contact us',
    'btn.learn_more'    => 'Learn more',
    'btn.send'          => 'Send',
    'btn.submit'        => 'Submit',
    'btn.back'          => 'Back',
    'btn.see_all'       => 'See all',
    'btn.our_services'  => 'Our services',
    'btn.free_quote'    => 'Free quote',
    'btn.view_details'  => 'View details',

    'available'         => 'Available for new projects',
    'results_guaranteed'=> 'Guaranteed results, respected deadlines.',

    /* ── Index ───────────────────────────────────────────────── */
    'home.hero_title'   => 'Transform<br>your digital<br><span class="gradient-text">vision.</span>',
    'home.hero_sub'     => 'Expert in web development, cybersecurity, digital marketing and professional training.',
    'home.stat_clients' => 'Satisfied clients',
    'home.stat_projects'=> 'Projects delivered',
    'home.stat_years'   => 'Years of experience',
    'home.about_badge'  => 'About Us',
    'home.about_title'  => 'Your Trusted Digital Partner',
    'home.about_sub'    => 'Netcrafter is a Nigerien company specialized in digital solutions for SMEs and institutions across the region.',
    'home.services_badge'=> 'Our Services',
    'home.services_title'=> 'Everything you need',
    'home.services_sub' => 'Complete solutions for your digital transformation',
    'home.cta_title'    => 'Ready to transform your digital presence?',
    'home.cta_sub'      => 'Join over 150 clients who trust us. Free and non-binding quote.',

    /* ── Services ────────────────────────────────────────────── */
    'services.badge'    => 'Our Services',
    'services.title'    => 'Complete Digital Solutions',
    'services.sub'      => 'From design to delivery, we manage every aspect of your digital project.',
    'services.dev_web'  => 'Web Development',
    'services.marketing'=> 'Digital Marketing',
    'services.security' => 'Security & CCTV',
    'services.network'  => 'Networks & Infra',
    'services.training' => 'Professional Training',
    'services.maintenance'=>'IT Maintenance',

    /* ── Volets ──────────────────────────────────────────────── */
    'volets.badge'      => 'Our Sectors',
    'volets.title'      => 'Areas of Excellence',
    'volets.sub'        => 'We operate across 6 major technology domains to cover all your needs.',

    /* ── Portfolio ───────────────────────────────────────────── */
    'portfolio.badge'   => 'Portfolio',
    'portfolio.title'   => 'Our Work',
    'portfolio.sub'     => 'Discover some of our recent projects.',
    'portfolio.filter_all'=> 'All',

    /* ── Devis ───────────────────────────────────────────────── */
    'devis.badge'       => 'Free Quote',
    'devis.title'       => 'Get Your Quote',
    'devis.sub'         => 'Answer a few questions and receive an estimate within 24 hours.',
    'devis.name'        => 'Full name',
    'devis.email'       => 'Email address',
    'devis.phone'       => 'Phone',
    'devis.company'     => 'Company (optional)',
    'devis.service'     => 'Desired service',
    'devis.budget'      => 'Estimated budget',
    'devis.message'     => 'Project description',
    'devis.send'        => 'Send my request',
    'devis.success'     => 'Your request has been sent! We will reply within 24 hours.',

    /* ── Index extra ────────────────────────────────────────── */
    'home.what_we_do'   => 'What we do',
    'home.what_we_master'=> 'What we master',
    'home.experts_title'=> 'Technical Expertise',
    'home.trust'        => 'They trust us',
    'home.testimonials' => 'What our clients say',
    'home.tech_title'   => 'Technologies we master',
    'home.volets_badge' => 'Our ecosystem',
    'home.volets_title' => '3 Sectors, <span class="gradient-text">1 Vision</span>',
    'home.cta_badge'    => 'Take action now',
    'home.cta_action'   => 'Your next project starts <span class="gradient-text">now</span>',
    'home.cta_action_sub'=> "Let's discuss your needs and build together the solution that will propel your business.",
    'home.devis_24h'    => 'Free quote — 24h',
    'home.whatsapp_direct'=> 'WhatsApp',
    'home.need_solution'=> 'Do you need one of these solutions?',
    'home.all_services' => 'All our services',
    'home.see_our_work' => 'See our work',
    'home.see_all_projects'=> 'See all projects',
    'home.portfolio_soon'=> 'Portfolio coming soon.',
    'home.ecosystem'    => 'Our ecosystem',
    'home.stat_done'    => 'Projects completed',
    'home.stat_exp'     => 'Of expertise',

    /* ── Services page extra ─────────────────────────────────── */
    'services.design'   => 'Graphic Design',
    'services.it'       => 'IT Services',
    'services.hero_sub' => 'Complete digital solutions, from design to deployment. Local expertise, international standards.',
    'services.cta_badge'=> 'Ready to start?',
    'services.cta_title'=> 'Ready to start <span class="gradient-text">your project?</span>',
    'services.cta_sub'  => 'Contact us today for a free personalized quote.',

    /* ── Volets extra ────────────────────────────────────────── */
    'volets.our_org'    => 'Our organization',
    'volets.cta_title'  => 'Questions about our sectors?',
    'volets.cta_sub'    => 'Contact us for personalized guidance.',

    /* ── Portfolio labels ────────────────────────────────────── */
    'pf.all'            => 'All',
    'pf.dev_web'        => 'Dev Web',
    'pf.webview'        => 'WebView',
    'pf.ia_chatbot'     => 'AI & Chatbot',
    'pf.whatsapp'       => 'WhatsApp',
    'pf.gestion'        => 'Management',
    'pf.suivi'          => 'Tracking',
    'pf.design'         => 'Design',
    'pf.securite'       => 'Security',

    /* ── Devis selects ───────────────────────────────────────── */
    'devis.budget_ph'   => 'Select a range',
    'devis.b_under50'   => 'Under 50,000 FCFA',
    'devis.b_50_100'    => '50,000 – 100,000 FCFA',
    'devis.b_100_300'   => '100,000 – 300,000 FCFA',
    'devis.b_300_500'   => '300,000 – 500,000 FCFA',
    'devis.b_over500'   => 'Over 500,000 FCFA',
    'devis.delay_ph'    => 'Select a timeline',
    'devis.d_urgent'    => 'Urgent (under 2 weeks)',
    'devis.d_1m'        => '1 month',
    'devis.d_2_3m'      => '2–3 months',
    'devis.d_flex'      => 'Flexible / To be discussed',

    /* ── Devis services ──────────────────────────────────────── */
    'devis.svc_web'     => 'Web Development',
    'devis.svc_web_sub' => 'Sites, apps, e-commerce',
    'devis.svc_mkt'     => 'Digital Marketing',
    'devis.svc_mkt_sub' => 'Ads, social media, content',
    'devis.svc_design'  => 'Graphic Design',
    'devis.svc_design_sub'=> 'Flyers, logos, branding',
    'devis.svc_secu'    => 'Security & Surveillance',
    'devis.svc_secu_sub'=> 'Cameras, alarms, access control',
    'devis.svc_it'      => 'IT Services',
    'devis.svc_it_sub'  => 'Maintenance, network, cloud',
    'devis.svc_form'    => 'Training',
    'devis.svc_form_sub'=> 'Custom training programmes',

    /* ── Home services (section Our Services) ────────────────── */
    'home.svc1_title'   => 'Web Development',
    'home.svc1_desc'    => 'Showcase sites, e-commerce, custom web apps tailored to your goals.',
    'home.svc1_i1'      => 'Corporate & showcase sites',
    'home.svc1_i2'      => 'Custom web apps',
    'home.svc1_i3'      => 'Full e-commerce',
    'home.svc2_title'   => 'Digital Marketing',
    'home.svc2_desc'    => 'Advertising campaigns and growth strategies to boost your online sales.',
    'home.svc2_i1'      => 'Facebook & Google Ads',
    'home.svc2_i2'      => 'Social media management',
    'home.svc2_i3'      => 'Content strategy',
    'home.svc3_title'   => 'Graphic Design',
    'home.svc3_desc'    => 'Professional visual identity, flyers, banners and impactful materials.',
    'home.svc3_i1'      => 'Flyers & leaflets',
    'home.svc3_i2'      => 'Visual identity',
    'home.svc3_i3'      => 'Banners & vinyl prints',
    'home.svc4_title'   => 'Security & Surveillance',
    'home.svc4_desc'    => 'Video surveillance, alarm systems and IT security solutions.',
    'home.svc4_i1'      => 'CCTV video surveillance',
    'home.svc4_i2'      => 'Alarm systems',
    'home.svc4_i3'      => 'Access control',
    'home.svc5_title'   => 'Networks & Telephony',
    'home.svc5_desc'    => 'Design and deployment of networks and PABX telephone systems.',
    'home.svc5_i1'      => 'Network cabling',
    'home.svc5_i2'      => 'PABX telephony',
    'home.svc5_i3'      => 'Server configuration',
    'home.svc6_title'   => 'IT Maintenance',
    'home.svc6_desc'    => 'Preventive maintenance, hardware repair and system customisation.',
    'home.svc6_i1'      => 'Preventive maintenance',
    'home.svc6_i2'      => 'Hardware repair',
    'home.svc6_i3'      => 'PC customisation',

    /* ── Portfolio extra ─────────────────────────────────────── */
    'portfolio.featured'=> 'Featured projects',
    'portfolio.all_proj'=> 'All projects',
    'portfolio.no_cat'  => 'No projects in this category yet.',
    'portfolio.see_proj'=> 'View project',
    'portfolio.similar' => 'Similar project?',
    'portfolio.cta_badge'=> 'Your project',
    'portfolio.cta_title'=> 'Have a <span class="gradient-text">similar project?</span>',
    'portfolio.cta_sub' => 'Contact us for a free quote and let\'s discuss your idea.',
    'portfolio.see_all' => 'See all projects',
    'portfolio.stat_done'=> 'Projects completed',
    'portfolio.stat_sat' => 'Satisfied clients',
    'portfolio.stat_tech'=> 'Technologies mastered',

    /* ── Devis extra ─────────────────────────────────────────── */
    'devis.form_badge'  => '100% free, no commitment',
    'devis.form_title'  => 'Quote Form',
    'devis.fill_below'  => 'Fill in the information below',
    'devis.info_step'   => 'Your information',
    'devis.services_step'=> 'Requested services',
    'devis.select_svcs' => 'Select one or more services:',
    'devis.project_step'=> 'Project details',
    'devis.budget_label'=> 'Estimated budget',
    'devis.delay_label' => 'Desired timeline',
    'devis.desc_label'  => 'Project description',
    'devis.how_found'   => 'How did you find us?',
    'devis.reset'       => 'Reset',
    'devis.send_request'=> 'Send my request',
    'devis.why_us'      => 'Why choose us?',
    'devis.contact_dir' => 'Contact us directly',
    'devis.testimonials'=> 'What our clients say',
    'devis.faq'         => 'Frequently asked questions',
    'devis.company_opt' => 'Your company name (optional)',
    'devis.desc_placeholder'=> 'Describe your needs, goals and expectations...',
    'devis.step_info'   => 'Information',
    'devis.step_svcs'   => 'Services',
    'devis.step_project'=> 'Project',

    /* ── Shop ────────────────────────────────────────────────── */
    'shop.title'        => 'Shop',
    'shop.subtitle'     => 'Equipment and technology solutions',
    'shop.search'       => 'Search a product...',
    'shop.filters'      => 'Filters',
    'shop.category'     => 'Category',
    'shop.all_cats'     => 'All categories',
    'shop.sort'         => 'Sort by',
    'shop.newest'       => 'Newest',
    'shop.price_asc'    => 'Price: low to high',
    'shop.price_desc'   => 'Price: high to low',
    'shop.in_stock'     => 'In stock only',
    'shop.no_results'   => 'No products found.',
    'shop.add_cart'     => 'Add to cart',
    'shop.add_fav'      => 'Wishlist',
    'shop.in_cart'      => 'In cart',
    'shop.out_stock'    => 'Out of stock',
    'shop.details'      => 'Details',
    'shop.buy'          => 'Buy',
    'shop.cart_title'   => 'My Cart',
    'shop.cart_empty'   => 'Your cart is empty',
    'shop.cart_empty_sub'=> 'Browse our shop to add products.',
    'shop.total'        => 'Total',
    'shop.subtotal'     => 'Subtotal',
    'shop.shipping'     => 'Shipping',
    'shop.free_ship'    => 'Free',
    'shop.checkout'     => 'Proceed to checkout',
    'shop.continue'     => 'Continue shopping',
    'shop.remove'       => 'Remove',
    'shop.qty'          => 'Qty',
    'shop.fav_title'    => 'My Wishlist',
    'shop.fav_empty'    => 'No favourites yet',
    'shop.fav_empty_sub'=> 'Click the heart on a product to save it.',
    'shop.clear_fav'    => 'Clear wishlist',
    'shop.view_cart'    => 'View my cart',
    'shop.checkout_title'=> 'Complete order',
    'shop.order_summary'=> 'Order summary',
    'shop.delivery_info'=> 'Delivery information',
    'shop.payment'      => 'Payment',
    'shop.place_order'  => 'Place order',
    'shop.order_success'=> 'Order placed successfully!',
    'shop.stock_low'    => 'Only',
    'shop.stock_low2'   => 'left in stock',

    /* ── Formation ───────────────────────────────────────────── */
    'form.title'        => 'Training',
    'form.subtitle'     => 'Develop your digital skills',
    'form.search'       => 'Search a training...',
    'form.all_levels'   => 'All levels',
    'form.beginner'     => 'Beginner',
    'form.intermediate' => 'Intermediate',
    'form.advanced'     => 'Advanced',
    'form.free_only'    => 'Free only',
    'form.subscribe'    => 'Enrol',
    'form.continue'     => 'Continue',
    'form.enrolled'     => 'Enrolled',
    'form.per_month'    => '/ month',
    'form.free'         => 'Free',
    'form.modules'      => 'modules',
    'form.videos'       => 'videos',
    'form.duration'     => 'Duration',
    'form.level'        => 'Level',
    'form.language'     => 'Language',
    'form.login_title'  => 'Sign in',
    'form.login_sub'    => 'Access your training space',
    'form.register_title'=> 'Sign up',
    'form.register_sub' => 'Create your account',
    'form.phone'        => 'Phone',
    'form.password'     => 'Password',
    'form.confirm_pass' => 'Confirm password',
    'form.firstname'    => 'First name',
    'form.lastname'     => 'Last name',
    'form.remember'     => 'Remember me',
    'form.forgot'       => 'Forgot password?',
    'form.no_account'   => 'No account yet?',
    'form.has_account'  => 'Already have an account?',
    'form.dashboard'    => 'Dashboard',
    'form.my_formations'=> 'My trainings',
    'form.certificates' => 'Certificates',
    'form.profile'      => 'Profile',
    'form.logout'       => 'Sign out',
    'form.progress'     => 'Progress',
    'form.watch_now'    => 'Watch',
    'form.no_formations'=> 'No training available',
    'form.popular'      => 'Popular trainings',
    'form.all_formations'=> 'All trainings',
    'form.cert_download'=> 'Download certificate',
    'form.filters'      => 'Filters',
    'form.categories'   => 'Categories',
    'form.all_cats'     => 'All categories',
    'form.sort_by'      => 'Sort by',
    'form.sort_newest'  => 'Newest',
    'form.sort_price_asc'  => 'Price ascending',
    'form.sort_price_desc' => 'Price descending',
    'form.sort_alpha'   => 'Alphabetical',
    'form.apply_filters'=> 'Apply filters',
    'form.reset_filters'=> 'Reset filters',
    'form.search_btn'   => 'Search',
    'form.filter_btn'   => 'Filters',
    'form.results_for'  => 'Results for',
    'form.cat_label'    => 'Category:',
    'form.found'        => 'trainings found',
    'form.discover'     => 'Discover',
    'form.not_found_title' => 'No training found',
    'form.not_found_sub'   => 'We could not find any training matching your criteria. Try adjusting your filters or search term.',
    'form.testimonials' => 'What our learners say',
    'form.cta_title'    => "Can't find your ideal training?",
    'form.cta_sub'      => 'Contact us to discuss your specific needs. We can create customised training paths for individuals and businesses.',
    'form.contact_us'   => 'Contact us',
    'form.pro_title'    => 'Professional Training',
    'form.pro_sub'      => 'Quality content designed by domain experts',
    'form.rhythm_title' => 'At Your Own Pace',
    'form.rhythm_sub'   => 'Learn whenever and wherever you want',
    'form.cert_title'   => 'Validated Certificates',
    'form.cert_sub'     => 'Receive a certificate upon completing your course',
    'form.community_title' => 'Community Forum',
    'form.community_sub'   => 'Exchange with trainers and other learners',
    'form.var_duration' => 'Variable duration',
    'form.see_all'      => 'View all trainings',
    'form.favorites'    => 'My favourite trainings',
    'form.notes_hint'   => 'Take notes on this video...',
],

]; // end $GLOBALS['nc_translations']
